WANDB_API_KEY=e54e11c5a3971ce143232dc777a77b7734c1d25e \
WANDB_BASE_URL=https://api.wandb.ai \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
python main.py \
  TYPE_OF_CONDITIONING='pos_embedding' \
  model=small \
  mode=train \
  data=openwebtext-split \
  parameterization=subs \
  model.length=128 \
  model.cond_dim_embedding=384 \
  eval.compute_generative_perplexity=True \
  sampling.num_sample_batches=8 \
  sampling.steps=128 \
  checkpointing.resume_from_ckpt=False \
  loader.global_batch_size=1024 \
  loader.batch_size=128 \
  loader.eval_batch_size=256 \
  trainer.val_check_interval=5000 \
  trainer.max_steps=1500000 \
  training.change_scheduler=true \
  text_embedder.use_text_embedder=True \
  text_embedder.model_name=sentence-transformers/all-MiniLM-L6-v2 \
  text_embedder.cond_dropout=0.0 \
  text_embedder.random_projection_dim=null \
  text_embedder.noise=0.1 \
  eval.generate_samples=True \
  data.wrap=False \
  vae_encoder.enabled=true \
  sub_conditioning.enabled=false \
  experiment_name='dit_attention_conditioning_changed_scheduler'
  # +embedding_cache_dir=/mnt/virtual_ai0001071-01239_SR006-nfs2/afedorov/projects/mdlm-fork/embedding_cache \
